# Generated by Django 4.0.2 on 2022-03-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemRefunds',
            fields=[
                ('order_item_refund_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('order_item_id', models.PositiveBigIntegerField()),
                ('order_id', models.PositiveBigIntegerField()),
                ('refund_amount_usd', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'order_item_refunds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('order_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('order_id', models.PositiveBigIntegerField()),
                ('product_id', models.PositiveSmallIntegerField()),
                ('is_primary_item', models.PositiveSmallIntegerField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cogs_usd', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'order_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('website_session_id', models.PositiveBigIntegerField()),
                ('user_id', models.PositiveBigIntegerField()),
                ('primary_product_id', models.PositiveSmallIntegerField()),
                ('items_purchased', models.PositiveSmallIntegerField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cogs_usd', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
    ]
