# Generated by Django 4.0.2 on 2022-03-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('product_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
