# Generated by Django 4.0.2 on 2022-03-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsitePageviews',
            fields=[
                ('website_pageview_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('website_session_id', models.PositiveBigIntegerField()),
                ('pageview_url', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'website_pageviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteSessions',
            fields=[
                ('website_session_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('user_id', models.PositiveBigIntegerField()),
                ('is_repeat_session', models.PositiveSmallIntegerField()),
                ('utm_source', models.CharField(blank=True, max_length=12, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=20, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=15, null=True)),
                ('device_type', models.CharField(blank=True, max_length=15, null=True)),
                ('http_referer', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'website_sessions',
                'managed': False,
            },
        ),
    ]
